/*
 * BreakBuddyJFrame.java
 *
 * Created on March 28, 2008, 1:41 PM
 */

package subBreakBuddy;

import Buddies.*;
import buddyLibrary.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author  Chen-Wei Kao
 */
public class BreakBuddyJFrame extends javax.swing.JPanel {
    
    
    private String correctIconPath="";
    private String wrongIconPath="";
    //variables used for guessing game
    private final int endNum = 100;
    private int targetNum;
    private int userGuess;
    private int countGuess = 0;
    
    Random rand = new Random();
    
   
    private String iconPath = "icons/";
    private ImageIcon correctIcon;
    private ImageIcon wrongIcon;
    private ImageIcon hintIcon;
    
    BreakBuddy breakBuddy;
    /** Creates new form BreakBuddyJFrame */
    public BreakBuddyJFrame(BreakBuddy breakBuddy) {
        initComponents();
        this.breakBuddy=breakBuddy;
        
        targetNum = rand.nextInt(endNum);
        
        ansIconLabel.setVisible(false);
        correctOrWrongTextArea.setVisible(false);
        
        correctIcon = new ImageIcon(iconPath + "correct.png");
        wrongIcon = new ImageIcon(iconPath + "wrong.png");
        hintIcon = new ImageIcon(iconPath + "hint.png");
        
        playAgainButton.setEnabled(false);
        

        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        playAgainButton = new javax.swing.JButton();
        countGuessLabel = new javax.swing.JLabel();
        ansTextField = new javax.swing.JTextField();
        questionIconLabel = new javax.swing.JLabel();
        ansIconLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        correctOrWrongTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        add(okButton);
        okButton.setBounds(360, 270, 80, 40);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        add(clearButton);
        clearButton.setBounds(470, 270, 80, 40);

        playAgainButton.setText("Play Again!");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });
        add(playAgainButton);
        playAgainButton.setBounds(340, 450, 130, 40);

        countGuessLabel.setFont(new java.awt.Font("Arial", 0, 12));
        countGuessLabel.setText("Number of guess: 0");
        add(countGuessLabel);
        countGuessLabel.setBounds(430, 140, 130, 15);
        add(ansTextField);
        ansTextField.setBounds(500, 200, 50, 20);

        questionIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chen-Wei Kao\\Desktop\\March 28\\branches\\workingProject3\\icons\\help.png")); // NOI18N
        add(questionIconLabel);
        questionIconLabel.setBounds(190, 190, 50, 50);

        ansIconLabel.setPreferredSize(new java.awt.Dimension(48, 48));
        add(ansIconLabel);
        ansIconLabel.setBounds(190, 340, 50, 50);

        jLabel1.setText("Please enter a number between 0 and 99 :");
        add(jLabel1);
        jLabel1.setBounds(250, 190, 240, 40);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        correctOrWrongTextArea.setBackground(jPanel1.getBackground());
        correctOrWrongTextArea.setColumns(20);
        correctOrWrongTextArea.setEditable(false);
        correctOrWrongTextArea.setFont(new java.awt.Font("Arial", 0, 12));
        correctOrWrongTextArea.setLineWrap(true);
        correctOrWrongTextArea.setRows(5);
        correctOrWrongTextArea.setWrapStyleWord(true);
        correctOrWrongTextArea.setAutoscrolls(false);
        correctOrWrongTextArea.setBorder(null);
        jScrollPane1.setViewportView(correctOrWrongTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(250, 350, 300, 60);

        jScrollPane2.setBackground(jPanel1.getBackground());
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(jPanel1.getBackground());
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 12));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("The computer will generate a random number between 0 and 99. You have to guess the number correctly within 10 times! Ready? GO!\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2);
        jScrollPane2.setBounds(230, 60, 300, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        try{
            userGuess=Integer.parseInt(ansTextField.getText());
        
        
            if (targetNum == userGuess) {
               // 


                ansIconLabel.setVisible(true);
                //ansIconLabel.setIcon(new ImageIcon(correctIconPath));
                correctOrWrongTextArea.setVisible(true);
                
                String boxContent = "BINGO! The number was " + targetNum + "." +
                        " You just used " + countGuess + " times only!";
                
                correctOrWrongTextArea.setText(boxContent);
                ansIconLabel.setIcon(correctIcon);
                
                countGuess = 0;
                
                targetNum = rand.nextInt(endNum);
                countGuessLabel.setText("Number of guess: " + countGuess);
                
                okButton.setEnabled(false);
                clearButton.setEnabled(false);
                playAgainButton.setEnabled(true);
            }
            else{
                countGuess++;
                if (countGuess < 10) {
                
                    ansIconLabel.setVisible(true);
                    //ansIconLabel.setIcon(new ImageIcon(wrongIconPath));
                    
                    correctOrWrongTextArea.setVisible(true);
                    String boxcontent="Sorry! Please guess again. ";
                    //if too small
                    if(userGuess < targetNum)
                        boxcontent= boxcontent + "It is smaller than the answer.";
                    else
                        boxcontent= boxcontent + "It is larger than the answer.";
                    
                    boxcontent= boxcontent + " You have " + (10 - countGuess) + " chances left!";
                    
                    correctOrWrongTextArea.setText(boxcontent);

                    ansIconLabel.setIcon(wrongIcon);
                    
                    countGuessLabel.setText("Number of guess: " + countGuess);
                }else {
                    ansIconLabel.setVisible(true);

                    correctOrWrongTextArea.setVisible(true);
                    String boxContent = "Sorry! You have guessed 10 times already. " +
                            "The number was " + targetNum + "The number has been re-generated now.";
                            
                    correctOrWrongTextArea.setText(boxContent);
                    ansIconLabel.setIcon(hintIcon);
                    
                    countGuessLabel.setText("Number of guess: 0");
                    countGuess = 0;
                    targetNum = rand.nextInt(endNum);
                    
                    okButton.setEnabled(false);
                    clearButton.setEnabled(false);
                    playAgainButton.setEnabled(true);
                }

            }
        }catch (Exception ex)
        {
            correctOrWrongTextArea.setText("Invalid input! Please enter again!");
            correctOrWrongTextArea.setVisible(true);
            ansIconLabel.setIcon(wrongIcon);
            ansIconLabel.setVisible(true);
        }
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        ansTextField.setText("");
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        // TODO add your handling code here:
        countGuess = 0;
        
        
                ansIconLabel.setVisible(true);
                ansIconLabel.setIcon(hintIcon);
                correctOrWrongTextArea.setVisible(true);
                correctOrWrongTextArea.setText("The number is now re-generagted!" +
                        "Please guess again!");


                targetNum = rand.nextInt(endNum);
                countGuessLabel.setText("Number of guess: " + countGuess);
                
                okButton.setEnabled(true);
                clearButton.setEnabled(true);
                playAgainButton.setEnabled(false);
}//GEN-LAST:event_playAgainButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansIconLabel;
    private javax.swing.JTextField ansTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextArea correctOrWrongTextArea;
    private javax.swing.JLabel countGuessLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JLabel questionIconLabel;
    // End of variables declaration//GEN-END:variables
    
}
