/*
 * startPanel.java
 *
 * Created on March 28, 2008, 7:17 PM
 */

package subBreakBuddy;

import Buddies.*;
import javax.swing.*;
/**
 *
 * @author  Chen-Wei Kao
 */
public class startPanel extends javax.swing.JPanel {
    
    BreakBuddy breakBuddy;
    
    
    /** Creates new form startPanel */
    public startPanel(BreakBuddy breakBuddy) {
        initComponents();
        //set image on the label
        //introLabel.setIcon(new ImageIcon ("questions/intro.jpg"));
        this.breakBuddy=breakBuddy;
        //introLabel.setSize(700, 700);
        //setSize(700,700);
        introLabel = new JLabel(new ImageIcon("questions/intro.jpg"));
    }
    
/*public static void main(String args[]){
          JFrame test = new JFrame();

         // test.setSize(700,700);
          test.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE  );
          test.add(new startPanel());
          //test.pack();
          test.setVisible(true);
      }    
  */  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        introLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(null);

        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        add(startButton);
        startButton.setBounds(320, 450, 150, 80);

        introLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chen-Wei Kao\\Desktop\\March 28\\branches\\workingProject3\\icons\\intro.jpg")); // NOI18N
        add(introLabel);
        introLabel.setBounds(40, 20, 695, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
       breakBuddy.startButtonClicked();
    }//GEN-LAST:event_startButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel introLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
    
}
