/*
 * TestMenu.java
 *
 * Created on February 14, 2008, 1:57 PM
 */

package selectionmenu;
import javax.swing.*;
import java.awt.event.*;
import java.io.*;
import java.lang.Exception;

/**
 *
 * @author  Chen-Wei Kao
 */
public class TestMenu  extends javax.swing.JPanel //implements ListSelectionModel 
{
    
    private JList choices;
    private DefaultListModel model;
    /*
    public void addListSelectionListener(javax.swing.event.ListSelectionListener)
    {
        return;
    }
    
    public void removeListSelectionListener(javax.swing.event.ListSelectionListener)
    {
        return;
    }
    public void valueChanged(ListSelectionModel e) {
       
    }*/
    
    public void listMouseClicked()
    {
       System.out.println(choices.getSelectedValue()); 
    }
    /** Creates new form TestMenu */
    public TestMenu() {
        initComponents();
        Object item[] = { "1", "2", "3"};
        
        choices = new JList(item);
        
        //model = new DefaultListModel();
        choices.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e)
            {
                listMouseClicked();
            }
            
            
        }
        );
        
        
        choices.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
        jScrollPane1.setColumnHeaderView(choices);
        
                
                
        jScrollPane1.repaint();      
        
        repaint();        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        newPlayer = new java.awt.Button();
        deletePlayer = new java.awt.Button();
        loginUser = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta1 = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(500, 500));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        newPlayer.setLabel("New Player");
        newPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPlayerActionPerformed(evt);
            }
        });

        deletePlayer.setLabel("Delete Player");
        deletePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlayerActionPerformed(evt);
            }
        });

        loginUser.setLabel("Login");
        loginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jta1.setColumns(20);
        jta1.setRows(5);
        jScrollPane2.setViewportView(jta1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(newPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(deletePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(loginUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(106, 106, 106)))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(722, 722, 722))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(708, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public String[] getChoices(){
        
        Object tempString[] = choices.getSelectedValues();
        
        String temp2String[] = new String [tempString.length];
        
        //loop all cells tempString
        for(int i = 0; i < tempString.length; i++)
        {
            temp2String[i] = (String) tempString[i];
        }
        //copy them to the temp2String
        
        return temp2String;
        
    }
    
    
    private void deletePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlayerActionPerformed
        // TODO add your handling code here:
        
        
        
}//GEN-LAST:event_deletePlayerActionPerformed

    private void loginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_loginUserActionPerformed

    private void newPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPlayerActionPerformed
        // TODO add your handling code here:
        JOptionPane jo = new JOptionPane();
        String userInput;
        
        userInput = jo.showInputDialog("Please enter the name of the new player");
        try {
        jta1.setText(null);
        File f1 = new File("user");
        if (!f1.exists()){
            f1.mkdir();
        }
        File f2 = new File(f1,"user.txt");
        
        FileReader fr = new FileReader(f2);
        BufferedReader br = new BufferedReader(fr);
        String output;
        
        String line = br.readLine();
        while (line != null){
            output = jta1.getText();
            jta1.setText(output + line + "\n");
            line = br.readLine();
            
        }

        br.close();
        
        FileWriter fw = new FileWriter(f2);
        BufferedWriter bw = new BufferedWriter(fw);
        
        output = jta1.getText() + userInput;
        bw.write(output);
        bw.newLine();
        bw.close();
        
        
        jta1.setText(output);
        }catch(IOException e){
        }
    }//GEN-LAST:event_newPlayerActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button deletePlayer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jta1;
    private java.awt.Button loginUser;
    private java.awt.Button newPlayer;
    // End of variables declaration//GEN-END:variables
    
}
